package com.sgs.ics.model.bc.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 20 13:47:20 IST 2022
// ---------------------------------------------------------------------
public interface SGSAppModule extends ApplicationModule {
    String loginValidationMethod(String user, String pass);
}

