package com.sgs.ics.model.bc.view.lookupVo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 09 08:11:43 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BuLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BuLovImpl() {
    }
}

