package com.sgs.ics.model.bc.view.lookupVo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 12 13:21:04 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CollectionPayerBUImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CollectionPayerBUImpl() {
    }
}

