package com.sgs.ics.model.bc.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 01 17:38:04 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NatureOfExpenseImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NatureOfExpenseImpl() {
    }
}

