package com.sgs.ics.model.bc.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 23 15:41:33 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsStdRateLineTblVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SgsStdRateLineTblVOImpl() {
    }
}

