package com.sgs.ics.model.bc.am;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 22 09:18:46 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SGSAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SGSAppModuleImpl() {
    }
    private static final ADFLogger LOG = ADFLogger.createADFLogger(SGSAppModuleImpl.class);
    /**
     * @param seqName
     * @return sequence next value
     */
    public int getDBSequence(String seqName) {
        Connection conn = null;
        PreparedStatement pst = null;
        try {
            String connectionUrl =
                "jdbc:sqlserver://localhost;instanceName=MSSQLSERVER;databasename=SGS;integratedSecurity=true;";
            conn = DriverManager.getConnection(connectionUrl);
            String sqlIdentifier = "select next value for " + seqName;
            pst = conn.prepareStatement(sqlIdentifier);

            ResultSet rs = pst.executeQuery();
            if (rs.next())
                rs.getInt(1);
            
            return rs.getInt(1);
        } catch (SQLException sqle) {
            LOG.severe(sqle);
        } finally {
            try {
                conn.close();
                pst.close();
            } catch (SQLException e) {
                LOG.severe(e);
            }
        }
        return 0;
    }

    /**
     * Container's getter for SgsUserAuthenticationVO1.
     * @return SgsUserAuthenticationVO1
     */
    public ViewObjectImpl getSgsUserAuthenticationVO() {
        return (ViewObjectImpl) findViewObject("SgsUserAuthenticationVO");
    }
}

